refactor: Change variable name FraudProofs to StateFraudProofs
rollkit/rollkit pull request #1091
Opened 2023-07-24 10:51 UTC by chandiniv1

closes #637

2023-07-24 12:46 UTC, Manav-Aggarwal requested changes
Left some comments. Rest looks good, thanks!

2023-07-24 12:46 UTC, Manav-Aggarwal commented on config/config.go
> +	StateFraudProofs bool              `mapstructure:"fraud_proofs"`
changing ``mapstructure:"fraud_proofs"`` to ``mapstructure:"state_fraud_proofs"`` would make sense as well.

2023-07-25 08:27 UTC, Manav-Aggarwal approved these changes
LGTM

2023-07-25 08:28 UTC, nashqueue approved these changes
Thank you for your contribution!

2023-07-25 08:38 UTC, merged