Spec for staking module differences
rollkit/rollkit pull request #1220
Opened 2023-10-02 03:42 UTC by S1nus

2023-10-03 16:41 UTC, S1nus commented on specs/src/specs/staking_module.md
> +## Assumptions and Considerations
"tendermint staking" does not exist. the ABCI App simply sets the validator set

2023-10-04 10:54 UTC, nashqueue requested changes
This spec aims to check how we use the staking module vs. how it is used in tendermint. Please elaborate on that.

2023-10-04 10:54 UTC, nashqueue commented on specs/src/specs/staking_module.md
> +## Assumptions and Considerations
Yes, we use the staking module for that.

2023-10-04 15:37 UTC, S1nus commented
> This spec aims to check how we use the staking module vs. how it is used in tendermint. Please elaborate on that.

we use it in exactly the same way?

2023-10-05 08:43 UTC, nashqueue commented
> > This spec aims to check how we use the staking module vs. how it is used in tendermint. Please elaborate on that.
> 
> don't we use it in exactly the same way?

The point of this spec is to exactly figure this out and to make sure to capture the nuances if there are differences.

2023-11-14 09:43 UTC, closed without merging

2023-11-14 09:43 UTC, S1nus commented
As of https://github.com/rollkit/rollkit/issues/1291, we decided that Rollkit vA will control the proposer entirely, ignoring all validator set updates from the ABCI app.

This is being implemented in the `Header.Verify(...)` method, where it enforces that the `ProposerAddress` must be equal to the `ProposerAddress` of the previous header. If implemented properly, this ensures the entire chain is signed by the same person (the centralized sequencer).