Add ConsensusParams updates handling logic
rollkit/rollkit pull request #1367
Opened 2023-11-28 05:07 UTC by Manav-Aggarwal

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-11-28 19:04 UTC, Manav-Aggarwal commented
Blocked on migration of main branch to `v0.50.x` so lint CI and testing CI fails currently but feel free to review.

2023-11-29 18:35 UTC, MSevey requested changes
lgtm just 2 quick tests

2023-11-29 18:35 UTC, MSevey commented on types/params.go
> +func ConsensusParamsValidateBasic(params cmtypes.ConsensusParams) error {
this should have a test to probe each of the checks.

2023-11-29 18:35 UTC, MSevey commented on types/serialization.go
> +func ConsensusParamsFromProto(pbParams cmproto.ConsensusParams) types.ConsensusParams {
this could also have a quick test

2023-11-29 19:24 UTC, tzdybal approved these changes
LGTM.

2023-12-02 02:07 UTC, MSevey approved these changes

2023-12-02 04:11 UTC, merged