fix(block/manager): limit block size to da max blob size
rollkit/rollkit pull request #1534
Opened 2024-02-09 01:06 UTC by tuxcanfly

## Overview

This PR limits the block max bytes to DA max blob size. Fixes #1428 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2024-02-09 14:23 UTC, Manav-Aggarwal requested changes

2024-02-09 14:23 UTC, Manav-Aggarwal commented on block/manager.go
> +
Let's also pass it through `ConsensusParamsValidateBasic` and make sure there's no errors.

2024-03-08 16:08 UTC, tuxcanfly commented
Should we add a config for a smaller default?: https://github.com/rollkit/rollkit/issues/1592

With or without a config I propose adding a static `~500KB` limit here instead. Having to call out the rpc just to initialize the manager seems inefficient.

2024-03-15 01:34 UTC, tuxcanfly commented
Following up in #1601

2024-03-15 01:34 UTC, closed without merging