update graph
rollkit/rollkit pull request #1635
Opened 2024-04-22 16:17 UTC by nashqueue

## Overview

This PR aims to be a starting point for a dependency graph update

The update is adding:
- more IBC work
- connecting Sequencing API and adding Execution 
- updates to overall progress

2024-04-25 21:39 UTC, tzdybal submitted a review, later dismissed
Looks like you worked with not-the-latest version of the file while updating.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/574">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                New Rollmint Header
Should be Rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/579">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/594">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                P2P Rollmint Headersync
Should be Rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                    P2P Rollmint Headers...
Should be Rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/362">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/514">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/514">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                                <a href="https://github.com/celestiaorg/rollmint/issues/571">
Should be rollkit/rollkit.

2024-04-25 21:39 UTC, tzdybal commented on specs/src/specs/dependency-graph.drawio.svg
> +                    New Rollmint Header...
Should be Rollkit.

2024-04-25 21:43 UTC, tzdybal reviewed
`avail-da` points to `credible neutrality` and at the same time `credible neutrality` points to `Other DA implementations`. I think 'other DA implementations` might be removed from the graph.

2024-04-25 21:50 UTC, tzdybal reviewed
Maybe you could introduce a color for "outcomes" that we're enabling, but not necessarily intend to build (like explorers, prover market, execution market, sequencer API implementations, etc)

2024-04-30 13:53 UTC, MSevey requested changes
pending Tomasz comments

2024-05-07 19:03 UTC, Manav-Aggarwal submitted a review, later dismissed

2024-05-07 19:08 UTC, tuxcanfly approved these changes

2024-05-07 19:38 UTC, tzdybal requested changes
One last `P2P Rollmint Headersync` to fix.

2024-05-07 19:42 UTC, Manav-Aggarwal approved these changes

2024-05-07 19:43 UTC, tzdybal approved these changes
:+1:

2024-05-07 19:55 UTC, merged