WIP on node interface seggregation
rollkit/rollkit pull request #1932
Opened 2024-11-27 14:28 UTC by yarikbratashchuk

WIP cleaning up #1896 #1897 #1898 #1899 #1900

2024-12-03 15:44 UTC, MSevey requested changes
Even though this is going on the feature branch for the exec_api, I think we should always have a passing CI. 

Otherwise we get into the habit of merging failing CI and get ourselves into a hole. 

If there are checks that need to be updated or removed for this feature branch we can do that, as long as we have a plan.

2024-12-03 15:44 UTC, MSevey commented on cmd/rollkit/commands/run_node.go
> -			// CI mode. Wait for 5s and then verify the node is running before calling stop node.
Why did you remove this? How are we handling the CI now?

2025-01-10 13:05 UTC, tzdybal reviewed
LGTM.

A lot of cleanup. We need to reintroduce tests (maybe rewrite them to some extend) ASAP (may be follow-up PR).

2025-01-20 23:17 UTC, tuxcanfly requested changes
needs lint fixes.

2025-01-21 13:08 UTC, tzdybal approved these changes
LGTM. My comment is optional and might be resolved in follow-up PR.

2025-01-21 14:37 UTC, yarikbratashchuk commented on node/execution_test.go
> +	txs, err := executor.GetTxs(ctx)
yes, will go in followup

2025-01-21 23:22 UTC, merged

2025-01-24 16:29 UTC, Manav-Aggarwal commented on node/execution_test.go
> +	txs, err := executor.GetTxs(ctx)
Please make a issue for this