Tzdybal/latest cosmos
rollkit/rollkit pull request #398
Opened 2022-05-09 19:49 UTC by allanperlee

Introduced light, experimental change to issue #357 . Will explore suggestions, if any. Thank you.

2022-05-10 16:14 UTC, allanperlee commented on rpc/client/client.go
> +		fmt.Errorf("failed to remove transaction from mempool: %w", err)
Yes, sir. Let me submit the changes momentarily

2022-05-11 13:30 UTC, tzdybal requested changes
Please add a test to `rpc/client/client_test.go`.
Hint 1: you can take a look at `TestCheckTx`, and create something similar, but with extra step of removing Tx.
Hint 2: There is `mempool.TxKey` function to get a key for Tx.

2022-05-11 17:30 UTC, allanperlee commented
@tzdybal I cannot find the `mempool.TxKey` method in the node directory, where can I find it? I want to learn if it takes parameters, and if a `node` is needed to use this method like in line 864.

2022-05-12 19:01 UTC, tzdybal commented
`mempool` is a package `github.com/celestiaorg/optimint/mempool/` (you probably need to import it). 

https://github.com/celestiaorg/optimint/blob/d0dcc50eb69b3d206f0be8d56154a0a36eee4ee3/mempool/clist_mempool.go#L756

2022-05-13 20:46 UTC, allanperlee commented
The package was imported and `TxKey` was used, but there is an error, stating that TxKey is not declared. Here is how I used it:
![2022-05-13](https://user-images.githubusercontent.com/48000848/168386956-2146deb4-55b5-47ec-823e-026e616e902f.png)

2022-05-16 13:40 UTC, tzdybal commented
Ah this was moved to different place. In type `Tx` in `"github.com/tendermint/tendermint/abci/types"`, there is a method `Key`.

2022-05-16 18:29 UTC, allanperlee commented
Yes, I committed the unit test. It fails with the wrong tx hash. It doesn't pass yet. I could not find the `Key` method in `github.com/tendermint/tendermint/abci/types` though. I chose the `TxKey`'s hashing instead provisionally. I found a method `Key` in `https://github.com/tendermint/tendermint/blob/master/types/tx.go#L23` , but the overriding or implementation of this interface is not found.

2023-06-09 11:22 UTC, nashqueue commented
Close stale PR cc: @tzdybal , Our client does not have a RemoveTx anymore so there is no Endpoint to be added.

2023-06-09 11:22 UTC, closed without merging